default:
  image:
    name: "docker:18"
    entrypoint: [""]
  services:
    - name: docker:20-dind
      alias: docker
      # in our experience although you'd assume this would be sufficient, this did
      # nothing to prevent connection errors without `DOCKER_TLS_CERTDIR` being set
      # to an empty string, and I would call that beyond mildly infuriating.
      command: ["--tls=false"]
  tags:
    - "tokend"

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  REGISTRY: registry.gitlab.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
  IMAGE_NAME: $REGISTRY:$CI_COMMIT_SHA
  IMAGE_NAME_TAG: $REGISTRY:$CI_COMMIT_TAG
  CONTAINER_RELEASE_IMAGE: $IMAGE_DOCKER:$CI_COMMIT_SHA


.before_script_template: &before_script_templ
  before_script:
    - docker version
    - docker login -u "${USER_DOCKER}" -p "${PASSWORD_DOCKER}"

stages:
  - build

Build And Publish:
  stage: build
  only:
    - branches
  <<: *before_script_templ
  script:
    - cd core
    - docker build -t "$CONTAINER_RELEASE_IMAGE" -f docker/Dockerfile .
    - docker push "$CONTAINER_RELEASE_IMAGE"
  except: [schedules]
  interruptible: true
