stages:
  - build
variables:
  CONTAINER_RELEASE_IMAGE: $IMAGE_DOCKER:$CI_COMMIT_SHA

build:
  image: docker:18
  services:
    - docker:18-dind
  stage: build
  script:
    - cd core
    - docker login -u "${USER_DOCKER}" -p "${PASSWORD_DOCKER}"
    - docker build -t "$CONTAINER_RELEASE_IMAGE" -f docker/Dockerfile .
    - docker push "$CONTAINER_RELEASE_IMAGE"
  tags:
    - "tokend" 